package main

import (
	"crypto/sha256"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

type openAPIDocument struct {
	Info struct {
		Version string `json:"version"`
	} `json:"info"`
	Paths map[string]map[string]json.RawMessage `json:"paths"`
}

func main() {
	specPath := flag.String("spec", "openapi/openapi.json", "canonical OpenAPI document")
	outputPath := flag.String("out", "sdk/go/envplanesdk/openapi_contract.gen.go", "generated Go output")
	flag.Parse()

	spec, err := os.ReadFile(*specPath)
	if err != nil {
		fatal(err)
	}
	var document openAPIDocument
	if err := json.Unmarshal(spec, &document); err != nil {
		fatal(err)
	}
	operations := make([]string, 0)
	for path, methods := range document.Paths {
		for method := range methods {
			method = strings.ToUpper(method)
			switch method {
			case "GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS":
				operations = append(operations, method+" "+path)
			}
		}
	}
	sort.Strings(operations)
	digest := fmt.Sprintf("%x", sha256.Sum256(spec))

	var source strings.Builder
	source.WriteString("// Code generated by cmd/sdkgen from the canonical OpenAPI document. DO NOT EDIT.\n\n")
	source.WriteString("package envplanesdk\n\n")
	fmt.Fprintf(&source, "const CanonicalOpenAPIVersion = %q\n", document.Info.Version)
	fmt.Fprintf(&source, "const CanonicalOpenAPISHA256 = %q\n\n", digest)
	source.WriteString("var CanonicalOperations = []string{\n")
	for _, operation := range operations {
		fmt.Fprintf(&source, "\t%q,\n", operation)
	}
	source.WriteString("}\n")

	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		fatal(err)
	}
	// #nosec G306 -- generated Go source is intentionally readable by repository users.
	if err := os.WriteFile(*outputPath, formatted, 0o644); err != nil {
		fatal(err)
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
